# PyTorch Fundamentals

## Variables

In [1]:
import torch
from torch.autograd import Variable

In [2]:
# requires_grad=True allows calculation of gradients with respect to a variable

a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
type(a)

torch.Tensor

In [4]:
b=Variable(torch.ones(2,2),requires_grad=True)

In [5]:
print(a+b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [6]:
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


## Gradients

In [7]:
x=Variable(torch.ones(2),requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

#### Gradients:

$y=5(x+1)^2$

backward should be called only on a scalar (1-element tensor) to calculate the gradients, and that is why `o` is defined as follows,

$o=\frac{1}{2}\sum_i(5(x_i+1)^2$

$\frac{\partial o}{\partial x_i}=\frac{1}{2}[10(x_i+1)]$

$\frac{\partial o}{\partial x_i}|_{x_i=1}= \frac{1}{2}[10(2)]=10$

In [8]:
y=5*(x+1)**2

In [9]:
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [10]:
o=(1/2)*torch.sum(y)

In [11]:
type(o)

torch.Tensor

In [12]:
o

tensor(20., grad_fn=<MulBackward0>)

In [13]:
# calculate the gradients

o.backward()

In [14]:
o

tensor(20., grad_fn=<MulBackward0>)

In [20]:
# access the value of gradient with respect to x
x.grad

tensor([10., 10.])

In [16]:
x

tensor([1., 1.], requires_grad=True)

In [17]:
print(x.grad)

tensor([10., 10.])


In [18]:
x=Variable(torch.ones(2),requires_grad=True)
y=5*(x+1)**2
o=(1/2)*torch.sum(y)
o.backward()
x.grad

tensor([10., 10.])