# Getting Started with PyTorch (Part 1)
By [Zahra Taheri](https://github.com/zahta), September 28, 2020

### Import libraries

In [1]:
import numpy as np
import torch

In [2]:
A = torch.ones((3,3), dtype=torch.float)
B = torch.ones((4,4), dtype=torch.double)
C = torch.ones((5,3,4), dtype=torch.short)

In [3]:
print('\n',A.dtype,'\n',B.dtype,'\n',C.dtype)


 torch.float32 
 torch.float64 
 torch.int16


In [4]:
A_a = np.random.rand(3,3)
A_t=torch.from_numpy(A_a).float()
print(A_t.dtype)
A_t

torch.float32


tensor([[0.3469, 0.5071, 0.8009],
        [0.8350, 0.6159, 0.6407],
        [0.9675, 0.1678, 0.4880]])

In [5]:
#NumPy seed
np.random.seed(42)

B_a = np.random.rand(4,4)
B_t=torch.from_numpy(B_a).double()
print(B_t.dtype)
B_t

torch.float64


tensor([[0.3745, 0.9507, 0.7320, 0.5987],
        [0.1560, 0.1560, 0.0581, 0.8662],
        [0.6011, 0.7081, 0.0206, 0.9699],
        [0.8324, 0.2123, 0.1818, 0.1834]], dtype=torch.float64)

In [6]:
#PyTorch seed
torch.manual_seed(42)

C_t = torch.randn((5,3,4))
print(C_t.dtype)
C_sh = C_t.short()
C_sh

torch.float32


tensor([[[ 1,  1,  0, -2],
         [ 0, -1,  0, -1],
         [ 0,  1,  0, -1]],

        [[ 0,  0,  0,  0],
         [ 1,  0,  0,  0],
         [ 0,  1,  0,  1]],

        [[ 1,  1,  0,  1],
         [ 0,  0,  0,  0],
         [-1,  0,  0,  1]],

        [[ 0,  0,  0,  0],
         [-1,  0,  0,  0],
         [ 0,  0,  1,  0]],

        [[ 1,  0,  2,  0],
         [ 1,  0,  0,  0],
         [ 0,  0,  0,  0]]], dtype=torch.int16)

In [7]:
with open('.\data\double_tensor.t','wb') as f:
   torch.save(B_t, f)

In [8]:
new_B_t = torch.load('.\data\double_tensor.t')

In [9]:
new_B_t

tensor([[0.3745, 0.9507, 0.7320, 0.5987],
        [0.1560, 0.1560, 0.0581, 0.8662],
        [0.6011, 0.7081, 0.0206, 0.9699],
        [0.8324, 0.2123, 0.1818, 0.1834]], dtype=torch.float64)

In [10]:
with open('.\data\double_tensor.t','rb') as f:
   new_B_t2 = torch.load(f)

In [11]:
new_B_t == new_B_t2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [12]:
torch.save(A_t, '.\data\mytensor.t')

In [13]:
new_A_t = torch.load('.\data\mytensor.t')

In [14]:
new_A_t

tensor([[0.3469, 0.5071, 0.8009],
        [0.8350, 0.6159, 0.6407],
        [0.9675, 0.1678, 0.4880]])

In [15]:
A_t==new_A_t

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
torch.save(C_sh[0,1,1], '.\data\element.t')

In [17]:
e = torch.load('.\data\element.t')

In [18]:
C_sh[0], e

(tensor([[ 1,  1,  0, -2],
         [ 0, -1,  0, -1],
         [ 0,  1,  0, -1]], dtype=torch.int16),
 tensor(-1, dtype=torch.int16))

In [19]:
import h5py

f = h5py.File('.\data\double_tensor2.t', 'w')
dataset = f.create_dataset('coords', data=B_t)
f.close()

In [20]:
f

<Closed HDF5 file>

In [21]:
dataset

<Closed HDF5 dataset>

In [22]:
f = h5py.File('.\data\double_tensor2.t', 'r')
dataset = f['coords']
some_parts = dataset[-3:]
some_parts

array([[0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [23]:
some_parts_t = torch.from_numpy(some_parts)
some_parts_t

tensor([[0.1560, 0.1560, 0.0581, 0.8662],
        [0.6011, 0.7081, 0.0206, 0.9699],
        [0.8324, 0.2123, 0.1818, 0.1834]], dtype=torch.float64)

In [24]:
f.close()

In [25]:
#PyTorch seed
torch.manual_seed(42)

B = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(B.dtype)
B

torch.int64


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
if torch.cuda.is_available():
    B_gpu = B.cuda()
else:
    print("There exists no GPU!")

There exists no GPU!


In [27]:
if torch.cuda.is_available():
    B_gpu2 = 3*B.to(device='cuda')
    print(B_gpu2)
else:
    print("There exists no GPU!")

There exists no GPU!


In [28]:
B

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
B.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.LongStorage of size 9]

In [30]:
B_transpose = B.t()

In [31]:
B_transpose.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.LongStorage of size 9]

In [32]:
id(B.storage()) == id(B_transpose.storage())

True

In [33]:
place = B.storage()
place[0] = 10
B

tensor([[10,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])

In [34]:
third_place = B[0,2]
print(third_place)
third_place.storage_offset()

tensor(3)


2

In [35]:
B.is_contiguous()

True

In [36]:
B_transpose.is_contiguous()

False

In [37]:
B_transpose

tensor([[10,  4,  7],
        [ 2,  5,  8],
        [ 3,  6,  9]])

In [38]:
B_transpose_cont = B_transpose.contiguous()
B_transpose_cont

tensor([[10,  4,  7],
        [ 2,  5,  8],
        [ 3,  6,  9]])

In [39]:
B_transpose_cont.is_contiguous()

True

In [40]:
B.stride()

(3, 1)

In [41]:
B_transpose.stride()

(1, 3)

In [42]:
T1 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float, requires_grad=True)
T2 = torch.ones(2,3)
T1_T2 = (T1*T2*3).sum()

T1_T2.backward()

print(T1_T2)

T1.grad

tensor(63., grad_fn=<SumBackward0>)


tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [43]:
T1 = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float)
T2 = torch.ones(2,3)
T1_T2 = (T1*T2*3).sum()

T1_T2.backward()

print(T1_T2)

T1.grad

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
T1.grad is None